sudo: required
before_install:
  - sudo apt-get install -y postgresql-server-dev-all
  - sudo apt-get install -y libpcap-dev
  - sudo apt-get install -y libmagickwand-dev
  - sudo apt-get install -y imagemagick
  - sudo apt-get install -y tesseract-ocr-all
language: ruby
rvm: # Rely upon .ruby-version
dist: trusty
